project/08_SeedData/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name="movie_list"),
    path('new/', views.new, name='new'),
    path('<int:movie_id>/', views.detail, name="detail"),
    path('<int:movie_id>/edit', views.edit, name="edit"),
    path('<int:movie_id>/scores/new/', views.score_new, name="score_new"),
    path('<int:movie_id>/scores/<int:score_id>/delete', views.score_delete, name='score_delete'),
]

project/08_SeedData/seeddata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

project/08_SeedData/movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.id}: {self.name}'
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return f'{self.id}: {self.title[:20]}'
        
        
class Score(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.id}:{self.content[:20]}'

project/08_SeedData/movies/forms.py
from django import forms
from .models import Genre, Movie, Score

class MovieModelForm(forms.ModelForm):
    
    class Meta:
        model = Movie
        fields = ['title', 'audience', 'poster_url', 'description', 'genre']
        widgets = {
            'title': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': "영화 제목을 입력하세요",
                }    
            ),
            'audience': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': "누적 관객수를 입력하세요",
                    'min': '0',
                }    
            ),
            'genre': forms.Select(
                attrs = {
                    'class':'form-control',
                }
            ),
            'poster_url': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': "URL을 입력하세요",
                }    
            ),
            'description': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': "영화를 소개해주세요",
                }    
            ),
        }
        
class ScoreModelForm(forms.ModelForm):
    
    class Meta:
        model = Score
        fields = ['content', 'score']
        widgets = {
            'content': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': "한줄평을 써주세요",
                }    
            ),
            'score': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'type':'number',
                    'min': "0",
                    'max': '5',
                    'step': 'any',
                }    
            ),
        }

project/08_SeedData/movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Genre, Movie, Score
from .forms import MovieModelForm, ScoreModelForm

# Create your views here.
def movie_list(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/list.html', context)
    
def new(request):
    if request.method == "POST":
        form = MovieModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:movie_list')
    else:
        form = MovieModelForm()
        return render(request, 'movies/form.html', {'form':form,})
        
def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    scores = movie.score_set.all()
    context = {
        'movie':movie,
        'scores':scores,
    }
    return render(request, 'movies/detail.html', context)
    
    
def edit(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    if request.method == "POST":
        form = MovieModelForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.id)
    else:
        form = MovieModelForm(instance=movie)
        return render(request, 'movies/form.html', {'form':form,})
    
    
def score_new(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        score = Score()
        score.content = request.POST.get('content')
        score.movie = movie
        score.score = request.POST.get('score')
        score.save()
    return redirect('movies:detail', movie.id)
    
def score_delete(request, movie_id, score_id):
    movie = get_object_or_404(Movie, id=movie_id)
    score = get_object_or_404(Score, id=score_id)
    if request.method == 'POST':
        score.delete()
    return redirect('movies:detail', movie.id)

project/08_SeedData/movies/templates/movies/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movies:movie_list' %}">Movie</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>



<div class="container container-fluid mt-3">
    {% block body %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

project/08_SeedData/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block title %}
    영화 상세 정보::{{ movie.title }}
{% endblock %}

{% block body %}
    <h1>영화 정보 조회</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="max-width: 287px; max-height: 413px">
                <img src="{{ movie.poster_url }}"
                     alt="{{ movie.poster_url }}"
                     class="card-img-top image-fluid">
            </div>
        </div>
        <div class="col-md-8 mt-5">
            <div class="row">
                <p class="col-2">영화 제목:</p>
                <p class="col-10">{{ movie.title }}<p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">누적 관객수:</p>
                <p class="col-10">{{ movie.audience }}</p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">장르:</p>
                <p class="col-10">{{ movie.genre.name }}</p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">평점:</p>
                <p class="col-10">{{ score.score }}</p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">영화 소개</p>
                <pre class="col-10">{{ movie.description }}</pre>
            </div>
            <hr>
        </div>
    </div>
    <div class="row float-right">
        <a href="{% url 'movies:movie_list' %}" class="detail-a btn btn-outline-success">목록</a>
        <a href="#" class="detail-a btn btn-outline-success ml-2 mr-2">삭제</a>
        <a href="{% url 'movies:edit' movie.id %}" class="detail-a btn btn-outline-success">수정</a>
    </div>
    <hr class="mt-5">

    {% include 'scores/_score.html' %}



{% endblock %}

project/08_SeedData/movies/templates/movies/form.html
{% extends 'movies/base.html' %}

{% block title %}
영화정보입력
{% endblock %}

{% block body %}
    <h1>영화정보</h1>
    <form action="
    {% if 'edit' in request.get_full_path %}
        {% url 'movies:edit' form.instance.id %}
    {% else %}
        {% url 'movies:new' %}
    {% endif %}
    " method="POST">
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success float-right">제출</button>
        {% csrf_token %}
    </form>

{% endblock %}

project/08_SeedData/movies/templates/movies/list.html
{% extends 'movies/base.html' %}

{% block title %}
영화 목록
{% endblock %}

{% block body %}
<p class="text-right"><a href="{% url 'movies:new' %}" class="btn btn-outline-success btn-lg sub" role="button">새 영화 등록</a></p>
{% if movies %}
        <section class="card-columns">
            
            {% for movie in movies %}
                <article class="card mb-2">
                    {% if movie.poster_url %}
                        <img src="{{ movie.poster_url }}"
                             alt="{{ movie.poster_url }}"
                             class="card-img-top image-fluid">
                    {% else %}
                        <img src="http://picsum.photos/32{{ forloop.counter }}/580/?random"
                             alt="random-image-{{ forloop.counter }}"
                             class="card-img-top image-fluid">
                    {% endif %}
                        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                    <!--<div class="card-body">-->
                    <!--      fa-2x/ 3x icon크기 키우기-->
                    <!--<i class="{{ posting.icon }} fa-2x"></i>-->
                    <!--</div>-->
                </article>
            {% endfor %}
        </section>
    {% endif %}
{% endblock %}

project/08_SeedData/movies/templates/scores/_score.html
<div id="scoreUI">
    <div id="scoreForm">
        {# form태그 안에서 enter를 사용하면 자동으로 submit이 이뤄지기 때문에 따로 버튼이 필요 없다#}
        <form action="{% url 'movies:score_new' movie.id %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <label for="score">평점매기기: </label>
                <input type="text" class='ml-3' id="score_content" name="content" placeholder="한줄평을 써주세요" minlength="10px" autofocus>
                <!--{# autofocus : detail페이지에 오면 자동으로 댓글입력창에 커서가 위치한다. #}-->
                <input type="number" class="form-control ml-2" min="0" max="5" name="score" step="any"
                       style="width: 60px">
                <button type="submit" class="ml-2 btn btn-outline-success">Submit</button>
            </div>
        </form>
    </div>
    <hr>
    <div id="scoreList">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">한줄평</th>
              <th scope="col">평점</th>
            </tr>
          </thead>
          <tbody>
            
            {% if scores %}
                {% for score in scores %}
                <tr>
                    <td>{{score.id}}</td>
                    <td>{{score.content}}</td>
                    <td>{{score.score}}</td>
                
                </tr>    
                {% endfor %}
            {% endif %}
              
          </tbody>
        </table>
        


    </div>
</div>