project/09_moviepjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.user_list, name="user_list"),
    path('<int:user_id>', views.people, name="people"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/followings/', views.followings, name="followings"),
    path('<int:user_id>/followers/', views.followers, name="followers"),
]

project/09_moviepjt/movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

project/09_moviepjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:movie_id>/', views.detail, name="detail"),
    path('<int:movie_id>/scores/new', views.score_create, name="score_create"),
    path('<int:movie_id>/scores/<int:score_id>/delete', views.score_delete, name="score_delete"),
]

project/09_moviepjt/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
   from_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")
   to_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers")

project/09_moviepjt/movies/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
        
class Score(models.Model):
    content = models.CharField(max_length=200)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    
    

project/09_moviepjt/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)
        

project/09_moviepjt/movies/forms.py
from django import forms
from .models import Score


class ScoreForm(forms.ModelForm):
    
    class Meta:
        model = Score
        fields = ['content', 'value',]

project/09_moviepjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .models import User

from .forms import UserCustomCreationForm


# Create your views here.
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {
        'form': user_form,
        'sign': "up",
    }
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {
        'form': login_form,
        'sign': "in",
    }
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')
    
@login_required
def user_list(request):
    users = User.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'accounts/userlist.html', context)
    
def people(request, user_id):
    people = get_object_or_404(User, id=user_id)
    followers_count = people.followers.count()
    followings_count = people.followings.count()
    scores = people.score_set.all()
    context = {
        'people':people,
        'scores':scores,
        'followings_count':followings_count,
        'followers_count':followers_count
    }
    
    return render(request, 'accounts/people.html', context)
    
def follow(request, user_id):
    person = get_object_or_404(User, pk=user_id) # 내가 팔로우 하고자 하는 사람
    
    # 만약 현재 유저가 해당 유저를 이미 팔로우하고 있었으면,
    if request.user in person.followings.all(): # 내가 person의 팔로워들 중에 있으면
        #   ---> 팔로우 취소
        request.user.followers.remove(person)
        person.followings.remove(request.user)
        # 아니면,
    else:
        #   ---> 팔로우
        request.user.followers.add(person)
        person.followings.add(request.user)
    return redirect('accounts:people', person.id)
    
    
@login_required
def followings(request, user_id):
    people = get_object_or_404(User, id=user_id)
    following_users = people.followings.all()
    context = {
        'follow_users': following_users,
    }
    return render(request, 'accounts/followlist.html', context)
    
@login_required
def followers(request, user_id):
    people = get_object_or_404(User, id=user_id)
    follower_users = people.followers.all()
    context = {
        'follow_users': follower_users,
    }
    return render(request, 'accounts/followlist.html', context)

project/09_moviepjt/movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Movie, Score
from .forms import ScoreForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Create your views here.
def list(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/list.html', context)
    
    
# TODO: 평점 max, min제어필요
def detail(request, movie_id):
    
    movie = get_object_or_404(Movie, pk=movie_id)
    score_form = ScoreForm()
    context = {
        'movie' : movie,
        'score_form': score_form,
    }
    return render(request, 'movies/detail.html', context)
    
    
@login_required
@require_POST
def score_create(request, movie_id):
    form = ScoreForm(request.POST)
    if form.is_valid():
        score = form.save(commit=False)
        score.user = request.user
        score.movie_id = movie_id
        score.save()
    else:
        return redirect('movies:list')
    return redirect('movies:detail', movie_id)
    
@login_required
def score_delete(request, movie_id, score_id):
    score = Score.objects.get(pk=score_id)
    if score.user == request.user:
        score.delete()
    return redirect('movies:detail', movie_id)

project/09_moviepjt/accounts/templates/accounts/followlist.html
{% extends 'base.html' %}

{% block body %}

<h1></h1>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">UserName</th>
    </tr>
  </thead>
  <tbody>
    {% for user in follow_users %}
      <tr>
        <th scope="row">-</th>
        <td>{{ user.username }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

project/09_moviepjt/accounts/templates/accounts/forms.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% if sign == "up" %}
    <input class="btn btn-success" type="submit" value="Sign up">
  {% else %}
    <input class="btn btn-success" type="submit" value="Sign in">
  {% endif %}
</form>

{% if sign == "up" %}
  <p class="mt-5"> If you already have account</p>
  <a href="{% url 'accounts:login' %}" class="btn btn-success">Sign in</a>
{% elif sign == "in" %}
  <p class="mt-5"> If you don't have account</p>
  <a href="{% url 'accounts:signup' %}" class="btn btn-success">Sign up</a>
{% endif %}

{% endblock %}

project/09_moviepjt/accounts/templates/accounts/people.html
{% extends 'base.html' %}

{% block body %}

<form class="mb-5">
    <h1유저화 정보 조회</h1>
    <div class="row">
      <p class="col-2">ID:</p>
      <p class="col-10">
        {{people.username}}
        <!-- 만약 현재 접속한 유저가 해당 페이지의 유저를이미 팔로우 한 경우, -->
        {% if user != people %}
          {% if user in people.followings.all %}
            <a class="btn btn-outline-primary" href="{% url 'accounts:follow' people.id %}">언팔로우</a>
          {% else %}
            <a class="btn btn-primary" href="{% url 'accounts:follow' people.id %}">팔로우</a>
          {% endif %}
        {% endif %} 
      <p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">이메일:</p>
        <p class="col-10">{{people.email}}</p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">following:</p>
        <p class="col-10"><a href="{% url 'accounts:followings' people.id %}">{{followings_count}}</a></p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">follower:</p>
        <p class="col-10"><a href="{% url 'accounts:followers' people.id %}">{{followers_count}}</a></p>
    </div>
    <hr>
    
    
    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">영화제목</th>
      <th scope="col">한줄평</th>
      <th scope="col">평점</th>
    </tr>
  </thead>
  <tbody>
    {% for score in scores %}
      <tr>
        <th scope="row">{{ score.movie }}</th>
        <td>{{ score.content }}</td>
        <td>{{ score.value }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
    
    
    
    
    <a href="{% url 'accounts:user_list' %}" class="detail-a btn btn-outline-success">목록</a>
    
</form>

{% endblock %}

project/09_moviepjt/accounts/templates/accounts/userlist.html
{% extends 'base.html' %}



{% block body %}


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">UserName</th>
      <th scope="col">Follow</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
      <tr>
        <th scope="row">{{ user.id }}</th>
        <td><a href="{% url 'accounts:people' user.id %}">{{ user.username }}</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>





{% endblock %}

project/09_moviepjt/movie_pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans|Jua|Sunflower:300" rel="stylesheet">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/favicon-96x96.png' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="screen">
  <title>영화추천사이트</title>
</head>
<body>
  
  {% include 'nav.html' %}
  
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
    
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
</body>
</html>

project/09_moviepjt/movie_pjt/templates/nav.html
<!-- Navigation Bar start -->
<nav class="navbar navbar-expand-lg navbar-default sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'movies:list' %}">영화추천시스템</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movies:list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}        
      <li class="nav-item">
        <a class="nav-link" href="../accounts/">유저 목록</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:people' user.id %}">{{ user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{% url 'accounts:signup' %}">Sign up</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
<!-- Navigation Bar end-->
  

project/09_moviepjt/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<form class="mb-5">
    <h1>영화 정보 조회</h1>
    <div class="row">
        <p class="col-2">영화 제목:</p>
        <p class="col-10">{{movie.title}}<p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">누적 관객수:</p>
        <p class="col-10">{{movie.audience}}</p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">장르:</p>
        <p class="col-10">{{movie.genre}}</p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">포스터 이미지 URL:</p>
        <p class="col-10">{{ movie.poster_url }}</p>
    </div>
    <hr>
    <div class="row">
        <p class="col-2">영화 소개</p>
        <pre class="col-10">{{ movie.description }}</pre>
    </div>
    <hr>
    <a href="{% url 'movies:list' %}" class="detail-a btn btn-outline-success">목록</a>
    <a href="" class="detail-a btn btn-outline-success disabled">삭제</a>
    <a href="" class="detail-a btn btn-outline-success disabled">수정</a>
</form>

<form class="mb-2 ml-3" method="POST" action="{% url 'movies:score_create' movie.id %}">
  {% csrf_token %}
  <div class="row">
    <div class="col-10"><div class="row">{% bootstrap_form score_form %}</div></div>
    <div class="col-2"><button type="submit" class="align-middle btn btn-success ml-3">작성</button></div>
    
  </div>
  
</form>


<hr>

{% for score in movie.score_set.all %}
  <div class="row card-text">
    <p><strong>{{ score.user.username }}</strong>   {{ score.content }}  {{ score.value }}</p>
    {% if score.user == request.user %}
    <form action="{% url 'movies:score_delete' movie.id score.id %}" method="POST">
      <button class="ml-3 btn btn-danger">삭제</button>
      {% csrf_token %}
    </form>
    {% endif %}
  </div>
  {% empty %}
  <div>댓글이 없습니다.</div>
{% endfor %}




{% endblock %}

project/09_moviepjt/movies/templates/movies/list.html
{% extends 'base.html' %}


{% block body %}
  <h3 class="subtitle">Movies List</h3>

  <div class="row">
    {% for movie in movies %}
    <div class="col-lg-3 col-md-4 col-sm-6 card-setting">
      <div class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"></a>
        <div class="card-body">
          <h4>{{ movie.title }}</h4>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


{% endblock %}