project/07_MovieProject/MovieProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

project/07_MovieProject/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/delete', views.movie_delete, name='movie_delete'),


    path('<int:movie_id>/scores/create/', views.score_create, name='score_create'),
    path('<int:movie_id>/scores/<int:score_id>/delete', views.score_delete, name='score_delete'),
]

project/07_MovieProject/movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=100, default='')

    def __str__(self):
        return f'{self.id}: {self.name}'

class Movie(models.Model):
    title = models.CharField(max_length=100,default='')
    audience = models.IntegerField()
    poster_url = models.TextField(default='')
    description = models.TextField(default='')
    genre = models.ForeignKey(Genre, on_delete=False)

    def __str__(self):
        return f'{self.id}: {self.title}'

class Score(models.Model):
    content = models.CharField(max_length=100, default='')
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.score}'

project/07_MovieProject/movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Genre, Movie, Score

# Create your views here.
def movie_list(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/list.html', context)


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    scores = movie.score_set.all()
    context = {
        'movie': movie,
        'scores': scores,
    }
    return render(request, 'movies/detail.html', context)

def movie_delete(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:movie_list')
    else:
        return redirect('movies:movie_detail', movie.id)

def score_create(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        score = Score()
        score.content = request.POST.get('content')
        score.movie = movie
        score.score = request.POST.get('score')
        score.save()
    return redirect('movies:movie_detail', movie.id)

def score_delete(request, movie_id, score_id):
    movie = get_object_or_404(Movie, id=movie_id)
    score = get_object_or_404(Score, id=score_id)
    if request.method == 'POST':
        score.delete()
    return redirect('movies:movie_detail', movie.id)

project/07_MovieProject/movies/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<div class="container container-fluid">
    {% block body %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

project/07_MovieProject/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
    영화 상세 정보::{{ movie.title }}
{% endblock %}

{% block body %}
    <h1>영화 정보 조회</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="max-width: 287px; max-height: 413px">
                <img src="{{ movie.poster_url }}"
                     alt="{{ movie.poster_url }}"
                     class="card-img-top image-fluid">
            </div>
        </div>
        <div class="col-md-8 mt-5">
            <div class="row">
                <p class="col-2">영화 제목:</p>
                <p class="col-10">{{ movie.title }}<p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">누적 관객수:</p>
                <p class="col-10">{{ movie.audience }}</p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">장르:</p>
                <p class="col-10">{{ movie.genre.name }}</p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">평점:</p>
                <p class="col-10">{{ score.score }}</p>
            </div>
            <hr>
            <div class="row">
                <p class="col-2">영화 소개</p>
                <pre class="col-10">{{ movie.description }}</pre>
            </div>
            <hr>
        </div>
    </div>
    <div class="row float-right">
        <a href="{% url 'movies:movie_list' %}" class="detail-a btn btn-outline-success">목록</a>
        <a href="{% url 'movies:movie_delete' movie.id %}" class="detail-a btn btn-outline-success">
            삭제
        {% csrf_token %}
        </a>
        <a href="..." class="disabled detail-a btn btn-outline-success">수정</a>
    </div>
    <hr class="mt-5">

    {% include 'scores/_score.html' %}



{% endblock %}

project/07_MovieProject/movies/templates/movies/list.html
{% extends 'base.html' %}

{% block title %}
영화 목록
{% endblock %}

{% block body %}
{% if movies %}
        <section class="card-columns">
            {% for movie in movies %}
                <article class="card mb-2">
                    {% if movie.poster_url %}
                        <img src="{{ movie.poster_url }}"
                             alt="{{ movie.poster_url }}"
                             class="card-img-top image-fluid">
                    {% else %}
                        <img src="http://picsum.photos/32{{ forloop.counter }}/580/?random"
                             alt="random-image-{{ forloop.counter }}"
                             class="card-img-top image-fluid">
                    {% endif %}
                    <a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}</a>

{#                <div class="card-body">#}
{#                    fa-2x/ 3x icon크기 키우기#}
{#                    <i class="{{ posting.icon }} fa-2x"></i>#}
{#                </div>#}
                </article>
            {% endfor %}
        </section>
    {% endif %}
{% endblock %}

project/07_MovieProject/movies/templates/scores/_score.html
<div id="scoreUI">
    <div id="scoreForm">
        {# form태그 안에서 enter를 사용하면 자동으로 submit이 이뤄지기 때문에 따로 버튼이 필요 없다#}
        <form action="{% url 'movies:score_create' movie.id %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <label for="score">평점매기기: </label>
                <input type="text" class='ml-3' id="score_content" name="content" placeholder="한줄평을 써주세요" minlength="10px" autofocus>
                {# autofocus : detail페이지에 오면 자동으로 댓글입력창에 커서가 위치한다. #}
                <input type="number" class="form-control ml-2" min="0" max="5" name="score" step="any"
                       style="width: 60px">
                <button type="submit" class="ml-2 btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    <div id="scoreList">
        {% if scores %}
            {% for score in scores %}
                <hr>
                <div class="row ml-5">
                    {{ score.content }}, {{ score.score }}
                    {# 순서대로 넣거나 명시적으로 써줘야함 #}
                    <form action="{% url 'movies:score_delete' movie_id=movie.id score_id=score.id %}"
                          method="post">
                        {% csrf_token %}
                        <button type="submit" onclick="return confirm('삭제함?')">[x]</button>
                    </form>
                </div>
            {% endfor %}
        {% endif %}


    </div>
</div>